/*  Danny Soto j
	Fecha 13/04/2022
*/

/*Creámos la base de datos */
CREATE DATABASE SUPERMERCADODB
GO
USE SUPERMERCADODB
GO

/*Creámos tabla 01 EMPLEADOS*/
CREATE TABLE EMPLEADOS(
	ID_EMPLEADO	INT IDENTITY(1,1) PRIMARY KEY, /*Aumenta de 1 en 1 iniciando en 1*/
	NOMBRE	VARCHAR(20) NOT NULL,
	PRIMER_APELLIDO	VARCHAR(20) NOT NULL,
	SEGUNDO_APELLIDO	VARCHAR(20) NOT NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	CORREO VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(100) NULL,
	CARGO	VARCHAR(30) DEFAULT 'Cajero'NOT NULL,
	FECHA_INGRESO DATE DEFAULT GETDATE() NOT NULL,
	NOMBRE_USUARIO	VARCHAR(20) NOT NULL,
	CONTRASENIA	VARCHAR(15) NOT NULL,
	ESTADO	VARCHAR(3) DEFAULT 'ACT' NOT NULL
)
/*Creámos las restricciones de la tabla COLABORADORES*/
/*Los únicos CARGOS en los que se podrá registrar un colaborador son */
ALTER TABLE EMPLEADOS
ADD CONSTRAINT CHK_CARGO CHECK (CARGO IN('Cajero','Bodeguero','Administrador'));
/*La fecha no puede ser mayor a la fecha actual*/
ALTER TABLE EMPLEADOS
ADD CONSTRAINT CKH_FECHA_INGRESO CHECK(FECHA_INGRESO <= GETDATE());
/*El colaborador tendrá dos estados ACT cuando ingresa y INA al desligarse de la empresa*/
ALTER TABLE EMPLEADOS
ADD CONSTRAINT CHK_ESTADO CHECK (ESTADO IN ('INA','ACT')and ESTADO = upper(ESTADO));
GO
/*--------------------------------------------------------------------------------*/
/*Creámos tabla 02 PROVEEDORES*/
CREATE TABLE PROVEEDORES(
	ID_PROVEEDOR	INT IDENTITY(1,1) PRIMARY KEY,/*Por defecto es not null*/
	NOMBRE_PROVEEDOR	VARCHAR(20) NOT NULL,
	DIRECCION	VARCHAR(100) NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	EXTENSION	INT NULL,
	CORREO	VARCHAR(25) NULL,
	NUMERO_CUENTA	VARCHAR(25) NOT NULL,
	CODIGO_PRODUCTO VARCHAR(50) NOT NULL,
	DESCRIPCION	VARCHAR(100) NOT NULL
)
GO
/*--------------------------------------------------------------------------------*/
/*Creámos tabla 03 REGISTRO_PRODUCTOS*/
CREATE TABLE REGISTRO_PRODUCTOS(
	ID_REGISTROP	INT IDENTITY(1,1) PRIMARY KEY,
	ID_EMPLEADO	INT NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	ID_PRODUCTO	VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	CANTIDAD	INT NOT NULL,
	PRECIO_UNIDAD	DECIMAL(10,2) NOT NULL	
)
GO



/*AGREGAR LAS RELACIONES MEDIANTE VAMOS CREANDO LAS TABLAS
  PROBAR EL FUNCIONAMIENTO PARA QUE NO ME LLEGUE A GENERAR
  UN PROBLEMA AL FINAL, PORQUE DE SER ASÍ SERÍA MÁS DIFICIL
  EL PODER CONTROLARLO*/
/*Implementamos las relaciones entre las tabla*/
/*Agregamos la referencia de la tabla REGISTRO_PRODUCTOS la cual tiene relaciones con:
	-EMPLEADOS
	-PROVEEDORES
*/
ALTER TABLE REGISTRO_PRODUCTOS
ADD CONSTRAINT CHK_REGISTRO_PRODUCTOS_EMPLEADOS
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO);

ALTER TABLE REGISTRO_PRODUCTOS
ADD CONSTRAINT CHK_REGISTRO_PRODUCTOS_PROVEEDORES
FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR);
GO